### ISSUE TITLE
contribs and xtools

### ISSUE THREAD

**Issue by Operator873** [Operator873/CabalBot#18]
The !contribs and !xtools commands will need to be rebuilt. The trigger.group() has no len attribute and can't be counted.

**Comment by Operator873** [comment]
contribs is fixed. Need to address xtools still.

**Comment by Tks4Fish** [comment]
Xtools fixed by ef3ff5aa816bb79ba6aa8e1f1e593890f15af046.

**Comment by Operator873** [comment]
Reopened for merge tracking.

**Comment by Operator873** [comment]
Tested works.
