### ISSUE TITLE
Write af_feed function

### ISSUE THREAD

**Issue by Operator873** [Operator873/CabalBot#7]
Write a function that accepts two inputs, "bot" which contains the bot commands and "change" which accepts the EventStream data. The function should select the channel for the abuse filter feed from the below sqlite database table and send the report to the channel via the bot class. Bonus points for pretty format and colors.

At present, I'm not sure of the format EventStreams sends AbuseLog hits. So I don't know how the report would be handled.

The function should rely on a sqlite database table called "af_feed" which has two columns: "project" and "channel"

**Comment by Tks4Fish** [comment]
Done at cdf7a924275cdd0682f3e04187af62f7c1859ab2
